Simon-Initiative/authoring-server

src/main/java/edu/cmu/oli/content/contentfiles/writers/ResourceToXml.java

Fix issue with supporting content being lost when only containing an image
Steps to recreate issue:
* Create new assessment in xml with image in supporting content
* Touch redeploy.do
* Open new assessment in editor
* At this point, once the "notify" persistence action is triggered and the assessment is saved, the xml is changed and loses the supporting content. However, the json retains the `content` tag
* The json with the `content` tag is sent to the server and the <content> tag is lost because it is incorrectly read as empty
* At re-deploy/re-import, the xml is consumed and the supporting content is lost
risk: low
stability: stable

fix missing images issue

---

README.md
data/changelog/db.changelog-0.25.0.xml
docker-compose.yml
pom.xml
src/main/java/edu/cmu/oli/content/analytics/DatasetBuilder.java
src/main/java/edu/cmu/oli/content/contentfiles/StartupHook.java
src/main/java/edu/cmu/oli/content/contentfiles/writers/ResourceToXml.java

This PR runs the "find dataset packages" query across parent packages so that it will find data for packages cloned from course versions that do not have student data associated with them. Basically, the issue was that when you clone a package and try to create a dataset from the clone, it only looked for data from the initial clone point, not previous versions of the cloned-from package.
From the Jira ticket:
"The dataset creator looks for previous versions of a course by id so that datasets can be created if the latest version of a course has no active student data. However, when you clone a course from a version with no active data, the dataset creator simply looks for student data from that "cloned from" version without going back to previous versions which DO have data. We need to …

Cloned packages should create datasets from previous versions of cloned-from packages

---

pom.xml
service.example.envs
src/main/java/edu/cmu/oli/content/AppUtils.java
src/main/java/edu/cmu/oli/content/boundary/managers/WebResourceManager.java
src/main/java/edu/cmu/oli/content/contentfiles/readers/XmlToContentPackage.java
src/main/java/edu/cmu/oli/content/controllers/SVNSyncController.java
src/main/java/edu/cmu/oli/content/resource/builders/ContentPkgJsonReader.java

This PR to sprint-0.27.0 reverts apache tika version to 1.14, sets keycloak default secret and small refactoring to file type detection. 
Risk: low
Stability: high

Authoring 1891 revert apache tika version

---

src/main/java/edu/cmu/oli/content/contentfiles/writers/ResourceToXml.java
src/test/java/edu/cmu/oli/content/contentfiles/writers/ChoicePrefixingTest.java
src/test/resources/edu/cmu/oli/content/contentfiles/writers/response_mult.xml

This PR fixes the handling of response_mult elements - specifically the problem that when choice#value attribute values are being updated to prepend a "v" the corresponding match attributes of match elements of response_mult elements were not also updated.
The fix is relatively straightforward.  In additional to the "response" elements that a part might contain, we also apply the logic of updated "input" and "match" attributes to "match" elements that are descendents of response_mult.
The unit test attached failed without this fix, and then passes once the fix was in place.
RISK: Low, isolated to inline and summative assessment handling in a well-understood manner
STABILITY: High

update match elements in response_mult

---

src/main/java/edu/cmu/oli/content/contentfiles/writers/ResourceToXml.java
src/test/java/edu/cmu/oli/content/contentfiles/writers/ResourceToXmlTest.java
src/test/resources/edu/cmu/oli/content/contentfiles/writers/multi-part-assessment.json

This PR removes the error prone attempt to guarantee that each input-ref is allied to a corresponding response(s). Not a strictly necessary cleanup procedure.
Risk: Low
Stability: high

Authoring 1904 response reorder hotfix

---

src/main/java/edu/cmu/oli/content/analytics/DatasetBuilder.java
src/main/java/edu/cmu/oli/content/boundary/endpoints/AnalyticsResource.java
src/main/java/edu/cmu/oli/content/boundary/managers/AnalyticsResourceManager.java
src/main/resources/dataset/create-by-part.sql
src/main/resources/dataset/create-by-resource.sql

Depends on authoring-client branch
This PR allows the full dataset of a course to be exported / downloaded. The output is a zip archive with three files: **byPart**, **byResource**, and **bySkill**, each in the form of the magic spreadsheet. 
The processing is done "live" on the backend, rather than up front when the dataset is first created and saved to the database. After weighing the different options, this felt like the best decision:
- Existing datasets will be able to be downloaded without recreating the dataset
- More importantly, this allows the export to be flexible -- we can change the output based on user feedback (eg adding more calculated fields, or removing unnecessary ones) while keeping the same underlying dataset
- It also made the implementation simpler because it didn't …

Authoring 1872 download dataset

---

conf/content-service-conf.example.json
src/test/resources/edu/cmu/oli/content/contentfiles/writers/config.json

This PR adds in the urls for both thumbnail and full size for themes. 
RISK: Low
STABILITY: High, tested in conjunction with authoring-dev, authoring-client PRs and it works.
This has a dependence of /oli/assets directory existing that contains the images.

add in thumbnail and image urls for themes

---

src/main/java/edu/cmu/oli/content/boundary/endpoints/ContentPackageResource.java
src/main/java/edu/cmu/oli/content/boundary/endpoints/ContentResource.java
src/main/java/edu/cmu/oli/content/boundary/endpoints/DeveloperResource.java
src/main/java/edu/cmu/oli/content/boundary/endpoints/EdgeResource.java
src/main/java/edu/cmu/oli/content/boundary/endpoints/LDModelResource.java
src/main/java/edu/cmu/oli/content/boundary/endpoints/LockResource.java
src/main/java/edu/cmu/oli/content/boundary/endpoints/ResourceDelivery.java
src/main/java/edu/cmu/oli/content/boundary/endpoints/WebResource.java
src/main/java/edu/cmu/oli/content/boundary/managers/AnalyticsResourceManager.java
src/main/java/edu/cmu/oli/content/boundary/managers/ContentPackageManager.java
src/main/java/edu/cmu/oli/content/boundary/managers/ContentResourceManager.java
src/main/java/edu/cmu/oli/content/boundary/managers/DeveloperResourceManager.java
src/main/java/edu/cmu/oli/content/boundary/managers/EdgeResourceManager.java
src/main/java/edu/cmu/oli/content/boundary/managers/LDModelResourceManager.java
src/main/java/edu/cmu/oli/content/boundary/managers/LockResourceManager.java
src/main/java/edu/cmu/oli/content/boundary/managers/ResourceDeliveryManager.java
src/main/java/edu/cmu/oli/content/boundary/managers/WebResourceManager.java
src/main/java/edu/cmu/oli/content/controllers/DeployControllerImpl.java
src/main/java/edu/cmu/oli/content/models/persistance/entities/Dataset.java
src/main/java/edu/cmu/oli/content/models/persistance/entities/Resource.java
src/main/java/edu/cmu/oli/content/security/AppSecurityController.java
src/main/java/edu/cmu/oli/content/security/ContentPackageLockLookup.java
src/main/java/edu/cmu/oli/content/security/KeyCloakSecurityProxy.java

This looks like more changes than it is.
Basically, all I did was change any endpoint that receives a package guid to also be able to receive a packageId-version combo. If it's a packageId-version, it looks up the package and supplies the guid to any dependent methods.
I also changed some endpoints to be able to also accept a resource ID instead of a resource guid. If the server can't find a resource with the given guid, it looks up the resource in the given package by id.
Risk: medium
Stability: stable

Support routing by ID

---

src/main/java/edu/cmu/oli/content/boundary/managers/ContentResourceManager.java

This PR allows the deletion of resources that appear more than once in another resource. Example cases of this: an org that includes the same workbook age twice.  A workbook page that contains multiple xrefs to another workbook page, an assessment that contains two selects - each to the same external question pool.
The issue was the Collectors API in Java triggers an exception if it encounters duplicate keys when converting to a map.  I rewrote this in a more robust manner.
RISK: Low, isolated to just the fetchResourcesEdge routine.  
STABILITY: High, with this in place the delete function and warning about existing uses works correctly

account for duplicate keys

---

src/main/java/edu/cmu/oli/feedback/validators/FeedbackValidator.java

This PR removes the server side validation that a likert scale size must be an odd integer.
RISK: Low
STABILITY: High, tested and in conjunction with corresponding authoring-client branch one can now author surveys with even numbered likert scales

allow for even number size

---

src/main/java/edu/cmu/oli/assessment/InlineAssessmentDelivery.java

This PR adjusts the handling of response matching so that incorrect matches do not replace correct matches. The case that I was seeing involved two responses, one with a match of "<8" and a score of 1 and the other with a match of "*" and a score of zero.  When given the input value of "3", both matches do indeed match, because 3 is less than 8 and of course the * matches anything.  But the way that the logic is written starting at the original line 496, the last match replaces the results of a previous match. So in this case the * match which was incorrect, replaces the <8 match, which was correct!
I added logic to handle the "best match" correctly.  
NOTE: The only substantive changes that I have made are from lines 508 through 580 of the current file.  All other changes are the result …

replace score in part correctly

---

src/main/java/edu/cmu/oli/content/boundary/managers/ContentResourceManager.java

This PR eliminates the two calls to the EdgeController::validateNonValidatedEdges method - which is not strictly necessary and is taking a full second to execute on Echo. 
Also, I adjusted the persistence timing logging to use the logger as opposed to System.err.println.
RISK: Low
STABILITY: High

remove validate call, log as debug

---

src/main/java/edu/cmu/oli/content/analytics/DatasetBuilder.java
src/main/java/edu/cmu/oli/content/boundary/managers/AnalyticsResourceManager.java
src/main/java/edu/cmu/oli/content/models/persistance/entities/Dataset.java

**Problem**:
There are several problems that can come up when creating analytics datasets:
1. Some error paths fail silently
2. A failed dataset can get stuck and unable to be re-created
3. Courses with many course sections but low enrollments per section (e.g. `concepts_of_statistics` with ~150 course sections) can exceed the dataset creation query timeout.
**Solution**:
1. Wrap another section of server code with a try/catch to handle errors
2. The client and the server identified "processing" sections in different ways. We added a dataset "status" field later on, which the client was using correctly, but the server code which was written earlier didn't use this field and incorrectly identified some failed datasets as still in process, so they couldn't be restarted.
3. Expand the …

0.37.0 - Fix some improvement analytics errors

---

data/changelog/db.changelog-0.37.0.xml
data/changelog/db.changelog-master.xml
src/main/java/edu/cmu/oli/content/models/persistance/entities/ContentPackage.java
src/main/java/edu/cmu/oli/content/resource/builders/ContentPkgJsonReader.java
src/main/java/edu/cmu/oli/content/resource/builders/ContentPkgXmlReader.java
src/main/java/edu/cmu/oli/content/resource/builders/ContentPkgXmlWriter.java

client branch - same name, `language-hotfix`
Deploying courses causes a build error.
The main change is to go from saving the default/chosen foreign language from the language element on the content_package table and XML to a new misc JSON field in the database. The client had to be changed to use this new field.

fix language persistence

---

src/main/java/edu/cmu/oli/content/resource/builders/OptionsWriter.java

See client PR for description.
The change here is to keep empty preferences objects from throwing.

fix parsing empty jsonobject in preferences

---

src/main/java/edu/cmu/oli/content/boundary/managers/ContentResourceManager.java

This PR addresses an issue where creating a new organization via cloning/copying an existing on breaks the course package due a missing organization icon. Current cloning logic does not account for icon referenced by the organization.  The workaround in this PR is simply to delete the icon reference after cloning.

remove icon reference from cloned organization

---

src/main/java/edu/cmu/oli/content/boundary/endpoints/AnalyticsResource.java
src/main/java/edu/cmu/oli/content/boundary/endpoints/ContentPackageResource.java
src/main/java/edu/cmu/oli/content/boundary/endpoints/ContentResource.java
src/main/java/edu/cmu/oli/content/boundary/endpoints/DeveloperResource.java
src/main/java/edu/cmu/oli/content/boundary/endpoints/EdgeResource.java
src/main/java/edu/cmu/oli/content/boundary/endpoints/LDModelResource.java
src/main/java/edu/cmu/oli/content/boundary/endpoints/LockResource.java
src/main/java/edu/cmu/oli/content/boundary/endpoints/LongPollResource.java
src/main/java/edu/cmu/oli/content/boundary/endpoints/ResourceDelivery.java
src/main/java/edu/cmu/oli/content/boundary/endpoints/WebResource.java
src/main/java/edu/cmu/oli/content/boundary/managers/AnalyticsResourceManager.java
src/main/java/edu/cmu/oli/content/boundary/managers/ContentPackageManager.java
src/main/java/edu/cmu/oli/content/boundary/managers/ContentResourceManager.java
src/main/java/edu/cmu/oli/content/configuration/DedicatedExecutor.java
src/main/java/edu/cmu/oli/content/configuration/ExecutorExposer.java
src/main/java/edu/cmu/oli/content/contentfiles/DirectorysWatcher.java
src/main/java/edu/cmu/oli/content/contentfiles/MigrationProcessor.java
src/main/java/edu/cmu/oli/content/contentfiles/RevisionMigrationProcessor.java
src/main/java/edu/cmu/oli/content/contentfiles/readers/XmlToContentPackage.java
src/main/java/edu/cmu/oli/content/controllers/EdgesController.java
src/main/java/edu/cmu/oli/content/controllers/LDModelControllerImpl.java

This PR addresses the memory leak issue caused by weak thread pool tracking and management. It moves all one-of pools into global scope and switches all managed pools into application scoped bean.
Risk: low
Stability: high

Updated threadpooling to fix out of memory errors

---

src/main/java/edu/cmu/oli/content/resource/builders/OptionsWriter.java

**Problem**:
The title for the course Statistics 5.1 for UC Davis can not be edited.
https://echo.oli.cmu.edu/#UCDavisStats-5.1
**Solution**:
Some older courses imported into Echo do not have package metadata that conforms to the assumptions made when the server code was written to update it. 
In this case, a null pointer exception was being thrown when the server tried to update the package options (specifically, the course preferences).
I added a null check so that it only continues parsing preferences if preferences are not empty.
To test, I deployed the branch to Shattrath and imported the UC Davis stats course that doesn't work on Echo, and I can edit the title now.
**Wireframe/Screenshot**:
None.
**Risk**:
Low
**Areas of concern**:
None

HOTFIX 0.41.0 - Fix package metadata editing

---

src/main/java/edu/cmu/oli/content/models/persistance/JsonWrapper.java
src/main/java/edu/cmu/oli/content/resource/builders/OptionsWriter.java

This PR is a fix for a json serialization assumption which is the root cause to a class of problem whereby editing any aspect of a course package attributes (title, description etc) can end up with an invalid package.xml file, especially one that has a preference list.

Authoring 2257 empty preferences bug

---

src/main/java/edu/cmu/oli/assessment/builders/Assessment2Transform.java
src/main/java/edu/cmu/oli/assessment/evaluators/MatcherByType.java
src/main/java/edu/cmu/oli/assessment/evaluators/PrecisionMatcher.java
src/main/java/edu/cmu/oli/content/controllers/LDModelControllerImpl.java
src/test/java/edu/cmu/oli/content/resource/builders/ImageHotspotTransformTest.java
src/test/resources/edu/cmu/oli/content/resource/builders/test-resources/_m4_assess.xml

This PR fixes an issue with A2 to/from unified model transformation affecting image_hotspot type questions. It also addresses an issue with skills tagging where question parts have "title" tags. Now correctly locates the skills tag after title instead of incorrectly before title tag.

Authoring 2269 image hotspot fix

---

src/main/java/edu/cmu/oli/content/configuration/Configurations.java
src/main/java/edu/cmu/oli/content/controllers/LockControllerImpl.java
src/main/java/edu/cmu/oli/content/models/ResourceEditLock.java

This PR adjusts the lock management approach to remove the server cleanup of expired locks, with the net result that a user will only ever see the "This editing session has expired" if another user has acquired the lock after the five minute expiration period. 
With this PR in place I have tested to ensure the following scenarios work correctly:
Scenario A: Extended Locks:
1. User A acquires a lock and makes some edits
2. User A walks away from computer for any amount of time exceeding 5 minutes, leaving the editor open
3. User A returns and makes another edit.  The logic detects that an existing expired lock from the same user is present so it simply allows that lock to be updated and the user can continue to make edits.
Scenario B: Expired Lock acquisition:
1. User A acquires a lock and …

take a more passive approach to lock management

---

src/main/java/edu/cmu/oli/content/controllers/LDModelControllerImpl.java

PR for bug fix on production where missing objectives in LD model breaks Learning Dashboard render in some modules.

include objectives with no skills in ld export

---

src/main/java/edu/cmu/oli/content/AppUtils.java

Deployed on shattrath for testing. 
The error was found to be introduced by the escapeAmpersand routine. This is used in one place to post-process the xml translation to escape ampersands occurring outside of CDATA sections. To skip CDATA sections the routine uses Java regexp machinery to find CDATA sections, temporarily replace them with marker strings while saving them on a list, do the ampersand escaping over the revised document, and then replace the marker strings with the saved CDATA sections to put them back. The problem was that the replaceFirst routine used to patch the CDATA's back in treats its argument as a regexp, interpreting metacharacters like backslash, leading to the behavior we see (": \t" in a code block gets changed to ": t"). Using Matcher.quoteReplacement on the …

Fix to preserve backslash escapes in code blocks

---

src/main/java/edu/cmu/oli/content/analytics/DatasetBuilder.java

1. Change which skill model is used for dataset creation. Before this change, the dataset used the version of the course that the dataset is being created for. But if this course hasn't been deployed yet, it won't have a skill model, and there won't be any skills to tie data to. Now, the skills model is found from the previous version, if one exists. This is done by sorting the package versions from newest to oldest by date created, and then taking the second one. This change should fix the "missing skills" issue in the dataset generation.
2. Add logging in a bunch of places and update the message that is sent to the frontend when a dataset completes.

Change dataset creation skill model lookup logic

---

src/main/resources/dataset/find-packages.sql

Fix a dataset creation bug where the code assumes one variable substitution per line in sql

Fix a dataset creation bug

---

src/main/java/edu/cmu/oli/content/contentfiles/readers/XmlToContentPackage.java
src/test/java/edu/cmu/oli/content/resource/builders/FixModernLanguageImportTest.java

This PR adds a hack to move media elements out of "p" tags during package import processing.

Bug-fix: editor dropping media elements wrapped in p tags.
